### YamlMime:ManagedReference
items:
- uid: Global.GraphiteApplication
  commentId: T:Global.GraphiteApplication
  id: GraphiteApplication
  parent: Global
  children: []
  langs:
  - csharp
  - vb
  name: GraphiteApplication
  nameWithType: GraphiteApplication
  fullName: GraphiteApplication
  type: Class
  source:
    id: GraphiteApplication
    path: ''
    startLine: 10
  assemblies:
  - cs.temp.dll
  namespace: Global
  syntax:
    content: 'public class GraphiteApplication : MonoBehaviour'
    content.vb: >-
      Public Class GraphiteApplication
          Inherits MonoBehaviour
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
references:
- uid: Global
  name: Global
  nameWithType: Global
  fullName: Global
  nameWithType.vb: ''
  fullName.vb: ''
  name.vb: ''
