name: Example documentation

on: 
  push: 
    branches: 
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install DocFX
        run: choco install -y docfx

      - name: Use README.md as index.md
        run: cp README.md Documentation/index.md

      - name: Build
        run: docfx Documentation/docfx.json

      - name: Create .nojekyll file
        run: echo "" > Documentation/_site/.nojekyll

      - name: Upload site artifact
        uses: actions/upload-artifact@v2
        with:
          name: _site
          path: Documentation/_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download site artifact
        uses: actions/download-artifact@v2
        with:
          name: _site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _site
